# Generated by Django 3.0.7 on 2020-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Quarantine', 'Quarantine related'), ('Stigma', 'Stigma related'), ('Testing', 'Testing related')], default='Stigma', max_length=200),
        ),
    ]
